// src/content/themes/domestic-animals.ts
// verified: false — вміст згенеровано Claude, потребує перевірки носієм мови.

import type {VocabTheme} from '../types';

export const domesticAnimals: VocabTheme = {
  slug: 'domestic-animals',
  kind: 'vocab',
  emoji: '🐄',
  title: {uk: 'Свійські тварини', ru: 'Домашние животные'},
  hyName: 'ընտանի կենդանիներ',
  words: [
    {
      hy: 'կատու',
      translit: 'katu',
      uk: 'кіт',
      ru: 'кот',
      pos: 'noun',
      emoji: '🐱',
      verified: false,
    },
    {
      hy: 'շուն',
      translit: 'shun',
      uk: 'собака',
      ru: 'собака',
      pos: 'noun',
      emoji: '🐶',
      verified: false,
    },
    {
      hy: 'ձի',
      translit: 'dzi',
      uk: 'кінь',
      ru: 'лошадь',
      pos: 'noun',
      emoji: '🐴',
      verified: false,
    },
    {
      hy: 'կով',
      translit: 'kov',
      uk: 'корова',
      ru: 'корова',
      pos: 'noun',
      emoji: '🐮',
      verified: false,
    },
    {
      hy: 'ոչխար',
      translit: 'vokhkhar',
      uk: 'вівця',
      ru: 'овца',
      pos: 'noun',
      emoji: '🐑',
      verified: false,
    },
    {
      hy: 'խոզ',
      translit: 'khoz',
      uk: 'свиня',
      ru: 'свинья',
      pos: 'noun',
      emoji: '🐷',
      verified: false,
    },
    {
      hy: 'հավ',
      translit: 'hav',
      uk: 'курка',
      ru: 'курица',
      pos: 'noun',
      emoji: '🐔',
      verified: false,
    },
    {
      hy: 'բադ',
      translit: 'bad',
      uk: 'качка',
      ru: 'утка',
      pos: 'noun',
      emoji: '🦆',
      verified: false,
    },
    {
      hy: 'ճագար',
      translit: 'chagar',
      uk: 'кролик',
      ru: 'кролик',
      pos: 'noun',
      emoji: '🐰',
      verified: false,
    },
    {
      hy: 'այծ',
      translit: 'ayts',
      uk: 'коза',
      ru: 'коза',
      pos: 'noun',
      emoji: '🐐',
      verified: false,
    },
    {
      hy: 'էշ',
      translit: 'esh',
      uk: 'осел',
      ru: 'осёл',
      pos: 'noun',
      emoji: '🫏',
      verified: false,
    },
    {
      hy: 'սագ',
      translit: 'sag',
      uk: 'гусак',
      ru: 'гусь',
      pos: 'noun',
      emoji: '🪿',
      verified: false,
    },
    {
      hy: 'հնդկահավ',
      translit: 'hndkahav',
      uk: 'індик',
      ru: 'индейка',
      pos: 'noun',
      emoji: '🦃',
      verified: false,
    },
  ],
  passage: {
    hy: 'Ֆերմայում ապրում են շատ ընտանի կենդանիներ։ Կովն ու ոչխարն արածում են կանաչ դաշտում։ Շունն ու կատուն ապրում են մեր տանը։ Բադն ու սագն ջրի մոտ լողում են։ Ձին արագ է վազում, էշն՝ կամաց։',
    translit:
      'Fermaum aprum en shat yntani kendanianer. Kovn u vokhkharn aratsum en kanach dashtum. Shunn u katun aprum en mer tany. Badn u sagn jri mot loghum en. Dzin arag e vadzum, eshn\' kamats.',
    uk: 'На фермі живе багато свійських тварин. Корова і вівця пасуться на зеленому полі. Собака і кіт живуть у нашому домі. Качка і гусак плавають біля води. Кінь бігає швидко, осел — повільно.',
    ru: 'На ферме живёт много домашних животных. Корова и овца пасутся на зелёном поле. Собака и кот живут в нашем доме. Утка и гусь плавают у воды. Лошадь бегает быстро, осёл — медленно.',
  },
};