// src/content/themes/wild-animals.ts
// verified: false — вміст згенеровано Claude, потребує перевірки носієм мови.

import type { VocabTheme } from '../types';

export const wildAnimals: VocabTheme = {
  slug: 'wild-animals',
  kind: 'vocab',
  emoji: '🦁',
  title: { uk: 'Дикі тварини', ru: 'Дикие животные' },
  hyName: 'վայրի կենդանիներ',
  words: [
    {
      hy: 'առյուծ',
      translit: 'aryuts',
      uk: 'лев',
      ru: 'лев',
      pos: 'noun',
      emoji: '🦁',
      verified: false,
    },
    {
      hy: 'վագր',
      translit: 'vagr',
      uk: 'тигр',
      ru: 'тигр',
      pos: 'noun',
      emoji: '🐯',
      verified: false,
    },
    {
      hy: 'արջ',
      translit: 'arj',
      uk: 'ведмідь',
      ru: 'медведь',
      pos: 'noun',
      emoji: '🐻',
      verified: false,
    },
    {
      hy: 'գայլ',
      translit: 'gayl',
      uk: 'вовк',
      ru: 'волк',
      pos: 'noun',
      emoji: '🐺',
      verified: false,
    },
    {
      hy: 'աղվես',
      translit: 'aghves',
      uk: 'лис',
      ru: 'лиса',
      pos: 'noun',
      emoji: '🦊',
      verified: false,
    },
    {
      hy: 'փիղ',
      translit: 'pigh',
      uk: 'слон',
      ru: 'слон',
      pos: 'noun',
      emoji: '🐘',
      verified: false,
    },
    {
      hy: 'ժիրաֆ',
      translit: 'zhiraf',
      uk: 'жираф',
      ru: 'жираф',
      pos: 'noun',
      emoji: '🦒',
      verified: false,
    },
    {
      hy: 'կապիկ',
      translit: 'kapik',
      uk: 'мавпа',
      ru: 'обезьяна',
      pos: 'noun',
      emoji: '🐒',
      verified: false,
    },
    {
      hy: 'օձ',
      translit: 'odz',
      uk: 'змія',
      ru: 'змея',
      pos: 'noun',
      emoji: '🐍',
      verified: false,
    },
    {
      hy: 'արծիվ',
      translit: 'artsiv',
      uk: 'орел',
      ru: 'орёл',
      pos: 'noun',
      emoji: '🦅',
      verified: false,
    },
    {
      hy: 'եղջերու',
      translit: 'yeghjeru',
      uk: 'олень',
      ru: 'олень',
      pos: 'noun',
      emoji: '🦌',
      verified: false,
    },
    {
      hy: 'նապաստակ',
      translit: 'napastak',
      uk: 'заєць',
      ru: 'заяц',
      pos: 'noun',
      emoji: '🐇',
      verified: false,
    },
    {
      hy: 'դելֆին',
      translit: 'delfin',
      uk: 'дельфін',
      ru: 'дельфин',
      pos: 'noun',
      emoji: '🐬',
      verified: false,
    },
  ],
  passage: {
    hy: 'Վայրի կենդանիները ապրում են անտառներում ու սավաննաներում։ Արջն ու գայլն անտառի բնակիչներն են։ Փիղն ամենամեծ ցամաքային կենդանին է։ Առյուծն ու վագրն ուժեղ գիշատիչներ են։ Արծիվն երկնքում բարձր է թռչում։',
    translit:
      'Vayri kendaninern aprum en antarrnerum u savannanerum. Arjn u gayln antarri bnakich\'nern en. Pighn amenametsk tsamakayin kendanin e. Aryutsn u vagrn uzhegh gishatiuchner en. Artsivn yerkynkum bardzr e trchum.',
    uk: 'Дикі тварини живуть у лісах і саванах. Ведмідь і вовк — мешканці лісу. Слон — найбільша наземна тварина. Лев і тигр — могутні хижаки. Орел високо ширяє у небі.',
    ru: 'Дикие животные живут в лесах и саваннах. Медведь и волк — обитатели леса. Слон — самое большое наземное животное. Лев и тигр — могучие хищники. Орёл высоко парит в небе.',
  },
};